### PR TITLE
⬆️ Upgrades Z-Wave JS UI to v8.8.5

### PR DESCRIPTION
**Pull request by Vaarlion**
# Proposed Changes

Upgrades Z-Wave JS UI to v8.8.5

- https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.8.4
- https://github.com/zwave-js/zwave-js-ui/releases/tag/v8.8.5

### CODE REVIEW

**Comment by roblandry** [comment]
I was able to get this to work by adding:
  python3-dev=3.10.10-r0 and nodejs=18.14.1-r0

**Comment by Vaarlion** [comment]
Sorry, i'm having some work issue and didn't took the time to look at the result of the pipeline.

i don't know what's base is used for the hassio-addons image, but it look like the previous pkg version are nolonger available in the pkg repository.
Thank's @roblandry for finding working version !

I could build it and have it run, so i'm requesting a new pipeline run  :)

**Comment by frenck** [comment]
> Sorry, i'm having some work issue and didn't took the time to look at the result of the pipeline.

It also means you didn't test this at all, didn't you?

**Comment by frenck** [comment]
Alright, in that case, I'll close the PR. Please, don't make PRs you can't or haven't tested. It wastes time for not just yourself, but also for people that review and discuss PRs.
You ain't helping nobody by doing drive-by PRs.

../Frenck

**Comment by roblandry** [comment]
@Vaarlion I apologize for stealing your PR. My intentions were to wait it out, however, I required an update due to upstream changes. Im currently running my own version, in my main branch until the PRs all get merged.

Also, Frenck (intentionally not tagged) I apologize for posting on a closed PR, but it was my only means of commenting to the OP.

**Pull request closed without merging**
